### ISSUE TITLE
As a user, I want to be able to perform a search for a given recipe.

### ISSUE THREAD

**Issue by jakewest35** [ChicoState/What4Dinner#10]

**Comment by jakewest35** [comment]
Should this be closed? Did you end up figuring out the API call for the search?

**Comment by arose510** [comment]
I was not able to, i pushed what we had yesterday and merged it, didn’t mean to close the whole issue.Sent from my iPhoneOn Feb 28, 2023, at 7:49 PM, Jake West ***@***.***> wrote:﻿
Should this be closed? Did you end up figuring out the API call for the search?

**Comment by jakewest35** [comment]
Reopening issue as it isn't actually resolved yet.
